/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-06-23 15:39:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/gyujin/jsp2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web04/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/gyujin/jsp2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655135212964L));
    _jspx_dependants.put("/WEB-INF/views/./include/footer.jsp", Long.valueOf(1655657033764L));
    _jspx_dependants.put("/WEB-INF/views/./include/header.jsp", Long.valueOf(1655995319189L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <!-- 검색(메타) 정보 -->\n");
      out.write("    <meta name=\"url\" content=\"http://test.com\">\n");
      out.write("    <meta name=\"title\" content=\"제목\">\n");
      out.write("    <meta name=\"description\" content=\"설명\">\n");
      out.write("    <meta name=\"keywords\" content=\"키워드\">\n");
      out.write("    <!-- 오픈 그래프 -->\n");
      out.write("    <meta property=\"og:url\" content=\"http://test.com\">\n");
      out.write("    <meta property=\"og:title\" content=\"제목\">\n");
      out.write("    <meta property=\"og:description\" content=\"설명\">\n");
      out.write("    <meta property=\"og:image\" content=\"로고주소\">\n");
      out.write("	<title>메인 페이지</title>\n");
      out.write("	<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/gh/xpressengine/xeicon@2.3.1/xeicon.min.css\">\n");
      out.write("	<link href=\"resources/css/common.css\" rel=\"stylesheet\">\n");
      out.write("	<link href=\"resources/css/normalize.css\" rel=\"stylesheet\">\n");
      out.write("	<script src=\"resources/js/jquery-latest.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<div class=\"header_wrap\">\r\n");
      out.write("    <div class=\"header_top\">\r\n");
      out.write("        <h1>연세디에이지는 환자중심의 진료환경을 지향합니다.</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"util_menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("        <!--로그인 전 -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <!-- 로그인 후 -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <!-- 로그인이 관리자 일 경우 -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"header_bottom\" >\r\n");
      out.write("        <div class=\"logo\"><img src=\"resources/img/logo.png\" alt=\"로고\"></div>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">De:AGE ABOUT</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                	<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memu/sbu1\">De:AGE about</a></li>\r\n");
      out.write("                	<li><a href=\"sub1#2\">Dr. Yoon. hyo geun</a></li>\r\n");
      out.write("                	<li><a href=\"sub1#3\">Location(Map)</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">EXOSOME(CELL)</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                <li><a href=\"sub1#1\">CELL-UP SKIN BOOSTER</a></li>\r\n");
      out.write("                <li><a href=\"sub1#2\">LEFILLEO</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">LIFTING</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                <li><a href=\"sub1#1\">Laser Lifting</a></li>\r\n");
      out.write("                <li><a href=\"sub1#2\">Thread Lifting</a></li>\r\n");
      out.write("                <li><a href=\"sub1#3\">Newtera Lifting</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">SKIN</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                <li><a href=\"sub1#1\">기미·주근깨</a></li>\r\n");
      out.write("                <li><a href=\"sub1#2\">여드름·자국(홍조)</a></li>\r\n");
      out.write("                <li><a href=\"sub1#3\">여드름흉터·모공</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">PETTI</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                <li><a href=\"sub1#1\">FILTER</a></li>\r\n");
      out.write("                <li><a href=\"sub1#2\">BOTOX</a></li>\r\n");
      out.write("                <li><a href=\"sub1#3\">Sculptra</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">ANTI-AGING</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                <li><a href=\"sub1#1\">신호등주사</a></li>\r\n");
      out.write("                <li><a href=\"sub1#2\">Vitamins-D</a></li>\r\n");
      out.write("                <li><a href=\"sub1#3\">남성호르몬</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <a href=\"#\">COMMUNITY</a>\r\n");
      out.write("            <div class=\"submenu_wrap\">\r\n");
      out.write("                <div class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do\">Event·Notice</a></li>\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <li><a href=\"sub1#3\">Before&After</a></li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"ct\">\n");
      out.write("        <div class=\"ct_wrap\">\n");
      out.write("            <div class=\"main_fade\">\n");
      out.write("                <div class=\"fadebox\">\n");
      out.write("                    <div class=\"fade_btn_box\">\n");
      out.write("                        <span class=\"prev_btn\">prev</span>\n");
      out.write("                        <span class=\"next_btn\">next</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"fade_btn_box2\">\n");
      out.write("                        <span class=\"slider_btn\"></span>\n");
      out.write("                        <span class=\"slider_btn\"></span>\n");
      out.write("                        <span class=\"slider_btn\"></span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <img alt=\"img1\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/main_slide01.jpg\">\n");
      out.write("				<img alt=\"img1\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/main_slide02.jpg\">\n");
      out.write("				<img alt=\"img1\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/main_slide03.jpg\">\n");
      out.write("            </div>\n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"main_banner\">\n");
      out.write("            <div class=\"banner_item\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/main_banner01.jpg\" alt=\"\"></div>\n");
      out.write("            <div class=\"banner_item\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/main_banner02.jpg\" alt=\"\"></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"sub_btn_box_wrap\">\n");
      out.write("            <div class=\"sub_btn_box\">\n");
      out.write("                <span class=\"sub_prev_btn\"><</span>\n");
      out.write("                <span class=\"sub_next_btn\">></span>\n");
      out.write("                        \n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"sub_banner_view\">\n");
      out.write("            <div class=\"sub_banner\">\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>쁘띠성형</h1>\n");
      out.write("                    <p class=\"sub_txt1\">Botox</p>\n");
      out.write("                    <p class=\"sub_txt2\">잔주름, 사각턱, 종아리, 다한증까지 보톡스로 해결하세요</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide01.jpg\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>리프팅 레이저</h1>\n");
      out.write("                    <p class=\"sub_txt1\">RF</p>\n");
      out.write("                    <p class=\"sub_txt2\">콜라겐&세포 리빌더<br>RF Lifting</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide02.jpg\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>실리프팅</h1>\n");
      out.write("                    <p class=\"sub_txt1\">Thread lifting</p>\n");
      out.write("                    <p class=\"sub_txt2\">특허받은 고정실로 매끈한 얼굴라인을 만들어드립니다.</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide03.jpg\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>안티에이징</h1>\n");
      out.write("                    <p class=\"sub_txt1\">ANTI-AGING</p>\n");
      out.write("                    <p class=\"sub_txt2\">내몸에 맞는 1:1 맞춤<br>안티에이징주사</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide04.jpg\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>쁘띠성형</h1>\n");
      out.write("                    <p class=\"sub_txt1\">Filler</p>\n");
      out.write("                    <p class=\"sub_txt2\">코,이마,볼,무턱 입체적인 얼굴 완성<br>Filler</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide05.jpg\"\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>리프팅 레이저</h1>\n");
      out.write("                    <p class=\"sub_txt1\">HIFU</p>\n");
      out.write("                    <p class=\"sub_txt2\">리프팅과 피부개선을 동시에<br> HIFU Lifting</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide06.jpg\"\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sub_item\">\n");
      out.write("                    <h1>안티에이징</h1>\n");
      out.write("                    <p class=\"sub_txt1\">ANTI-AGING</p>\n");
      out.write("                    <p class=\"sub_txt2\">노화방지와 탄력을 동시에!<br>ANTI-AGING</p>\n");
      out.write("                    <div class=\"sub_imgbox\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/multi_slide07jpg\"\" alt=\"\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"main_about\">\n");
      out.write("            <div class=\"main_about_titbox\">\n");
      out.write("                <h3>아름다운 변화의 시작! 연세디에이지</h1>\n");
      out.write("                    <h1><span class=\"color1\">연구</span>하고 노력하는 <span class=\"color1\">윤효근 원장</span></h1>\n");
      out.write("                    <h2><span class=\"color2\">10년 이상의 진료 노하우</span>를 바탕으로 <span class=\"color2\">안전</span>하고<br>\n");
      out.write("                        건강한 피부를 <span class=\"color2\">책임</span>지겠습니다.</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"main_about_imgbox\">\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/main_about.png\" alt=\"\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"main_about_btnbox\">\n");
      out.write("                <a href=\"#\">자세히 보기</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"board_box\">\n");
      out.write("            <div class=\"review_box\">\n");
      out.write("                <div class=\"board_tit\">\n");
      out.write("                    <h2>Real Review\n");
      out.write("                        <a href=\"#\">+</a>\n");
      out.write("                    </h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"board_list\">\n");
      out.write("                    <table>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>시흥 은계 색소치료 피부…</td>\n");
      out.write("                                <td>2022-05-16</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>은계피부과 연세디에이지의…</td>\n");
      out.write("                                <td>2022-05-02</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>시흥 은계 색소치료 피부…</td>\n");
      out.write("                                <td>2022-04-20</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>시흥 은계 색소치료 피부…</td>\n");
      out.write("                                <td>2022-05-16</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>시흥 은계 색소치료 피부…</td>\n");
      out.write("                                <td>2022-05-16</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>시흥 은계 색소치료 피부…</td>\n");
      out.write("                                <td>2022-05-16</td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"news_box\">\n");
      out.write("                <div class=\"board_tit\">\n");
      out.write("                    <h2>News\n");
      out.write("                        <a href=\"#\">+</a>\n");
      out.write("                    </h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"board_list\">\n");
      out.write("                    <table>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>얼굴 동안(童顏) 만들어…</td>\n");
      out.write("                                <td>2022-03-29</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>얼굴 동안(童顏) 만들어…</td>\n");
      out.write("                                <td>2022-03-29</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>얼굴 동안(童顏) 만들어…</td>\n");
      out.write("                                <td>2022-03-29</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>얼굴 동안(童顏) 만들어…</td>\n");
      out.write("                                <td>2022-03-29</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>얼굴 동안(童顏) 만들어…</td>\n");
      out.write("                                <td>2022-03-29</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>얼굴 동안(童顏) 만들어…</td>\n");
      out.write("                                <td>2022-03-29</td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    \n");
      out.write("    <div class=\"main_customer\">  \n");
      out.write("        <div class=\"layout\">\n");
      out.write("            <div class=\"info\"> \n");
      out.write("                <h2>Contact Us</h2>\n");
      out.write("                <p class=\"txt\">경기도 시흥시 은계번영길 9, 4F 409~411 (은행동 골드웨이) 연세디에이지의원</p>\n");
      out.write("                <dl class=\"dl_style1\">\n");
      out.write("                    <dt><i class=\"icon\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/info_icon01.png\" alt=\"\"></i>전화</dt>\n");
      out.write("                    <dd>031.318.1013</dd><br>\n");
      out.write("                    <dt><i class=\"icon\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/info_icon02.png\" alt=\"\"></i>이메일</dt>\n");
      out.write("                    <dd>faceartist@daum.net</dd><br>\n");
      out.write("                    <dt><i class=\"icon\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/info_icon03.png\" alt=\"\"></i>카카오톡</dt>\n");
      out.write("                    <dd>연세디에이지의원</dd><br>\n");
      out.write("                    <dt><i class=\"icon\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/info_icon04.png\" alt=\"\"></i>진료시간</dt>\n");
      out.write("                    <dd>\n");
      out.write("                        <p><span>평&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;일</span>AM 10:00 ~ PM 07:00 <em class=\"p_color1\">(수요일 휴진)</em></p>\n");
      out.write("                        <p><span>토&nbsp;&nbsp;요&nbsp;&nbsp;일</span><em class=\"p_color2\">AM 10:00 ~ PM 03:00(점심시간 없이 진료)</em></p>\n");
      out.write("                        <p><span>점심 평일</span>PM 01:00 ~ PM 02:00</p>\n");
      out.write("                    </dd>\n");
      out.write("                </dl>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"location\">\n");
      out.write("            \n");
      out.write("                <div id=\"daumRoughmapContainer1619019048980\" class=\"map-wrap root_daum_roughmap root_daum_roughmap_landing\"></div>\n");
      out.write("\n");
      out.write("            \n");
      out.write("                <script charset=\"UTF-8\" class=\"daum_roughmap_loader_script\" src=\"https://ssl.daumcdn.net/dmaps/map_js_init/roughmapLoader.js\"></script>\n");
      out.write("\n");
      out.write("                <script charset=\"UTF-8\">\n");
      out.write("                	new daum.roughmap.Lander({\n");
      out.write("                		\"timestamp\" : \"1619019048980\",\n");
      out.write("                		\"key\" : \"25gjh\"\n");
      out.write("                	}).render();\n");
      out.write("                </script>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>   \n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            var subpos = 0;\n");
      out.write("\n");
      out.write("\n");
      out.write("            $(\".sub_prev_btn\").click(function () {\n");
      out.write("                if (subpos < 3) sub_right();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\".sub_next_btn\").click(function () {\n");
      out.write("                if (subpos > 0) sub_left();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            function sub_right() {\n");
      out.write("                $(\".sub_item\").animate({ left: \"-=288\" }, 500);\n");
      out.write("                subpos++\n");
      out.write("            }\n");
      out.write("            function sub_left() {\n");
      out.write("                $(\".sub_item\").animate({ left: \"+=288\" }, 500);\n");
      out.write("                subpos--\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function slider_ck() {\n");
      out.write("                var f1 = $(\".main_img\").eq(0).css(\"display\");\n");
      out.write("                var f2 = $(\".main_img\").eq(1).css(\"display\");\n");
      out.write("                var f3 = $(\".main_img\").eq(2).css(\"display\");\n");
      out.write("                var fs = 0;\n");
      out.write("                if (f1 === \"block\") {\n");
      out.write("                    fs = 1;\n");
      out.write("                } else if (f2 === \"block\") {\n");
      out.write("                    fs = 2;\n");
      out.write("                } else if (f3 === \"block\") {\n");
      out.write("                    fs = 3;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                if (fs === 1) {\n");
      out.write("                    $(\".slider_btn\").eq(0).css(\"background-color\", \"black\");\n");
      out.write("                    $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                    $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("                } else if (fs === 2) {\n");
      out.write("                    $(\".slider_btn\").eq(1).css(\"background-color\", \"black\");\n");
      out.write("                    $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                    $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("                } else if (fs === 3) {\n");
      out.write("                    $(\".slider_btn\").eq(2).css(\"background-color\", \"black\");\n");
      out.write("                    $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                    $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("            $(\".main_img\").eq(1).fadeOut();\n");
      out.write("            $(\".main_img\").eq(2).fadeOut();\n");
      out.write("            slider_ck();\n");
      out.write("\n");
      out.write("            var interval = setInterval(function () {\n");
      out.write("                next();\n");
      out.write("            }, 7000);\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            $(\".prev_btn\").click(function () {\n");
      out.write("                clearInterval(interval);\n");
      out.write("                prev();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\".next_btn\").click(function () {\n");
      out.write("                clearInterval(interval);\n");
      out.write("                next();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("            $(\".slider_btn\").eq(0).click(function () {\n");
      out.write("                clearInterval(interval);\n");
      out.write("                $(\".main_img\").eq(1).fadeOut(1000).delay(1000);\n");
      out.write("                $(\".main_img\").eq(2).fadeOut(1000).delay(1000);\n");
      out.write("                $(\".main_img\").eq(0).delay(1000).fadeIn(1000);\n");
      out.write("                $(\".slider_btn\").eq(0).css(\"background-color\", \"black\");\n");
      out.write("                $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\".slider_btn\").eq(1).click(function () {\n");
      out.write("                clearInterval(interval);\n");
      out.write("                $(\".main_img\").eq(0).fadeOut(1000).delay(1000);\n");
      out.write("                $(\".main_img\").eq(2).fadeOut(1000).delay(1000);\n");
      out.write("                $(\".main_img\").eq(1).delay(1000).fadeIn(1000);\n");
      out.write("                $(\".slider_btn\").eq(1).css(\"background-color\", \"black\");\n");
      out.write("                $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\".slider_btn\").eq(2).click(function () {\n");
      out.write("                clearInterval(interval);\n");
      out.write("                $(\".main_img\").eq(0).fadeOut(1000).delay(1000);\n");
      out.write("                $(\".main_img\").eq(1).fadeOut(1000).delay(1000);\n");
      out.write("                $(\".main_img\").eq(2).delay(1000).fadeIn(1000);\n");
      out.write("                $(\".slider_btn\").eq(2).css(\"background-color\", \"black\");\n");
      out.write("                $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            function prev() {\n");
      out.write("\n");
      out.write("                var f1 = $(\".main_img\").eq(0).css(\"display\");\n");
      out.write("                var f2 = $(\".main_img\").eq(1).css(\"display\");\n");
      out.write("                var f3 = $(\".main_img\").eq(2).css(\"display\");\n");
      out.write("                var fs = 0;\n");
      out.write("\n");
      out.write("                if (f1 === \"block\") {\n");
      out.write("                    fs = 1;\n");
      out.write("                } else if (f2 === \"block\") {\n");
      out.write("                    fs = 2;\n");
      out.write("                } else if (f3 === \"block\") {\n");
      out.write("                    fs = 3;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                switch (fs) {\n");
      out.write("                    case 1:\n");
      out.write("                        $(\".main_img\").eq(0).fadeOut(1000).delay(1000);\n");
      out.write("                        $(\".main_img\").eq(2).delay(1000).fadeIn(1000);\n");
      out.write("                        $(\".slider_btn\").eq(2).css(\"background-color\", \"black\");\n");
      out.write("                        $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                        $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                        break;\n");
      out.write("                    case 2:\n");
      out.write("                        $(\".main_img\").eq(1).fadeOut(1000).delay(1000);\n");
      out.write("                        $(\".main_img\").eq(0).delay(1000).fadeIn(1000);\n");
      out.write("                        $(\".slider_btn\").eq(0).css(\"background-color\", \"black\");\n");
      out.write("                        $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                        $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("                        break;\n");
      out.write("                    case 3:\n");
      out.write("                        $(\".main_img\").eq(2).fadeOut(1000).delay(1000);\n");
      out.write("                        $(\".main_img\").eq(1).delay(1000).fadeIn(1000);\n");
      out.write("                        $(\".slider_btn\").eq(1).css(\"background-color\", \"black\");\n");
      out.write("                        $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                        $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("                        break;\n");
      out.write("\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function next() {\n");
      out.write("\n");
      out.write("                var f1 = $(\".main_img\").eq(0).css(\"display\");\n");
      out.write("                var f2 = $(\".main_img\").eq(1).css(\"display\");\n");
      out.write("                var f3 = $(\".main_img\").eq(2).css(\"display\");\n");
      out.write("                var fs = 0;\n");
      out.write("\n");
      out.write("                if (f1 === \"block\") {\n");
      out.write("                    fs = 1;\n");
      out.write("                } else if (f2 === \"block\") {\n");
      out.write("                    fs = 2;\n");
      out.write("                } else if (f3 === \"block\") {\n");
      out.write("                    fs = 3;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                switch (fs) {\n");
      out.write("                    case 1:\n");
      out.write("                        $(\".main_img\").eq(0).fadeOut(1000).delay(1000);\n");
      out.write("                        $(\".main_img\").eq(1).delay(1000).fadeIn(1000);\n");
      out.write("                        $(\".slider_btn\").eq(1).css(\"background-color\", \"black\");\n");
      out.write("                        $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                        $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("                        break;\n");
      out.write("                    case 2:\n");
      out.write("                        $(\".main_img\").eq(1).fadeOut(1000).delay(1000);\n");
      out.write("                        $(\".main_img\").eq(2).delay(1000).fadeIn(1000);\n");
      out.write("                        $(\".slider_btn\").eq(2).css(\"background-color\", \"black\");\n");
      out.write("                        $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                        $(\".slider_btn\").eq(0).css(\"background-color\", \"#777\");\n");
      out.write("                        break;\n");
      out.write("                    case 3:\n");
      out.write("                        $(\".main_img\").eq(2).fadeOut(1000).delay(1000);\n");
      out.write("                        $(\".main_img\").eq(0).delay(1000).fadeIn(1000);\n");
      out.write("                        $(\".slider_btn\").eq(0).css(\"background-color\", \"black\");\n");
      out.write("                        $(\".slider_btn\").eq(1).css(\"background-color\", \"#777\");\n");
      out.write("                        $(\".slider_btn\").eq(2).css(\"background-color\", \"#777\");\n");
      out.write("                        break;\n");
      out.write("\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("  \r\n");
      out.write("    <div class=\"footer_wrap\">\r\n");
      out.write("        <div class=\"footer_top\" >\r\n");
      out.write("            <a href=\"#\" target=\"_blank\"><i class=\"xi-youtube-play xi-5x\"></i></a>\r\n");
      out.write("            <a href=\"#\" target=\"_blank\"><i class=\"xi-instagram xi-5x\"></i></a>\r\n");
      out.write("            <a href=\"#\" target=\"_blank\"><i class=\"xi-kakaotalk xi-5x\"></i></a>\r\n");
      out.write("            <a href=\"#\" target=\"_blank\"><i class=\"xi-message xi-5x\"></i></a>            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ft_bind\">\r\n");
      out.write("        <div class=\"footer_bottom\">\r\n");
      out.write("            <img src=\"resources/img/footer_logo.png\" alt=\"로고\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer_info\">\r\n");
      out.write("            <nav class=\"nav1\"><a href=\"#\" target=\"_blank\">개인정보정책</a></nav>\r\n");
      out.write("            <nav class=\"nav2\"><a href=\"#\" target=\"_blank\">이용약관</a></nav>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span>\r\n");
      out.write("                    <strong>주소 : </strong>\r\n");
      out.write("                    	경기도 시흥시 은계번영길 9, 4F 409~411(은행동 골드웨이)\r\n");
      out.write("                </span>\r\n");
      out.write("                <span>\r\n");
      out.write("                    <strong>E-mail : </strong>\r\n");
      out.write("                    	faceartist@daum.net\r\n");
      out.write("                </span>\r\n");
      out.write("                <br>\r\n");
      out.write("                <span>\r\n");
      out.write("                    <strong>사업자등록번호 : </strong>\r\n");
      out.write("                    647-16-01380\r\n");
      out.write("                </span>\r\n");
      out.write("                <span>\r\n");
      out.write("                    <strong>대표원장 : </strong>\r\n");
      out.write("                    	윤효근\r\n");
      out.write("                </span>\r\n");
      out.write("                <span>\r\n");
      out.write("                    <strong>의료기관명칭 : </strong>\r\n");
      out.write("                   	 연세디에이지의원\r\n");
      out.write("                </span>\r\n");
      out.write("                <span>\r\n");
      out.write("                    <strong>전화번호 : </strong>\r\n");
      out.write("                    	031.318.1013\r\n");
      out.write("                </span>\r\n");
      out.write("                <p>COPYRIGHT ⓒ2021 deageclinic All right Reserved</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" id=\"top_btn\">\r\n");
      out.write("                <img src=\"resources/img/gotop.jpg\" alt=\"버튼\">\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/home.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/./include/header.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path1");
      // /WEB-INF/views/./include/header.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/./include/header.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/./include/header.jsp(12,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/agreement.do\">회원가입</a></li>\r\n");
          out.write("            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\">로그인</a></li>\r\n");
          out.write("        \r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/./include/header.jsp(18,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty userid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        	<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read.do\">마이페이지</a></li>\r\n");
          out.write("            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a></li>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/./include/header.jsp(23,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        	<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/List.do\">회원 목록</a></li>\r\n");
          out.write("        	<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/list.do\">게시판 목록</a></li>\r\n");
          out.write("        	<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/databank/list.do\">자료실 목록</a></li>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/./include/header.jsp(96,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/databank/writeForm.do\">자료등록</a></li>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/./include/header.jsp(99,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname != 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/databank/writeForm.do\">Kakaotalk</a></li>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
